### ADMIN register

POST http://localhost:5501/auth/register
Content-Type: application/json

{
  "firstName": "admin",
  "lastName": "p",
  "email": "pppadmin@mern.space",
  "password": "secret"
}

### ADMIN login 

POST http://localhost:5501/auth/login
Content-Type: application/json

{
  "email": "radmin@mern.space",
  "password": "secret"
}

### self
GET http://localhost:5501/auth/self

###
POST http://localhost:5501/auth/refresh
Content-Type: application/json

### jwt keys converted
GET http://localhost:5501/.well-known/jwks.json

### for logout first login
POST http://localhost:5501/auth/login
Content-Type: application/json

{
  "email": "runi@mern.space",
  "password": "secret"
}

### then logout
POST http://localhost:5501/auth/logout

### register tenants
POST http://localhost:5501/tenants
Content-Type: application/json

{  
  "name": "john",
  "address": "CANADA"
}

### register users with tenant id

POST http://localhost:5501/users
Content-Type: application/json

{
    "firstName": "zane",
    "lastName": "p",
    "email": "zmanedoe@mern.space",
    "password": "password",
    "role": "customer",
    "tenantId": 3
}

### get users
GET http://localhost:5501/users/1