### ADMIN register
POST http://localhost:5501/auth/register
Content-Type: application/json

{
  "firstName": "janeett",
  "lastName": "doe",
  "email": "janettttbb@doemern.space",
  "password": "secret"
}

### ADMIN 1 login 
POST http://localhost:5501/auth/login
Content-Type: application/json

{
  "email": "rdmin@mern.space",
  "password": "secret"
}

### ADMIN 2
POST http://localhost:5501/auth/login
Content-Type: application/json

{
  "email": "runi@mern.space",
  "password": "secret"
}

### CUSTOMER

POST http://localhost:5501/auth/login
Content-Type: application/json

{
  "email": "janee@mern.space",
  "password": "secret"
}

### CUSTOMER 2
POST http://localhost:5501/auth/login
Content-Type: application/json

{
  "email": "zane@mern.space",
  "password": "secret"
}

### MANAGER REGISTER
POST http://localhost:5501/auth/register
Content-Type: application/json

{
  "firstName": "manager",
  "lastName": "doe",
  "email": "manager10@mern.space",
  "password": "secret",
  "role": "manager",
  "tenantId": "10"
}

### MANAGER
POST http://localhost:5501/auth/login
Content-Type: application/json

{
  "email": "manager10@mern.space",
  "password": "secret"
}


### self
GET http://localhost:5501/auth/self

###
POST http://localhost:5501/auth/refresh
Content-Type: application/json

### jwt keys converted
GET http://localhost:5501/.well-known/jwks.json

### for logout first login
POST http://localhost:5501/auth/login
Content-Type: application/json

{
  "email": "panda@mern.space",
  "password": "secret"
}

### then logout
POST http://localhost:5501/auth/logout

### register tenants
POST http://localhost:5501/tenants
Content-Type: application/json

{  
  "name": "april",
  "address": "usa"
}

### register users with tenant id

POST http://localhost:5501/users
Content-Type: application/json

{
    "firstName": "zane",
    "lastName": "p",
    "email": "aprildoe@mern.space",
    "password": "password",
    "role": "customer",
    "tenantId": 2
}

### get users
GET http://localhost:5501/users

### Get users with query params

GET http://localhost:5501/users?currentPage=4&perPage=10

### Get users with query params skip

GET http://localhost:5501/users?currentPage=4&skip=8

### Get usesr using search query

GET http://localhost:5501/users?currentPage=1&perPage=10&q=jane

### Get users using search query & role

GET http://localhost:5501/users?q=runi&role=admin

### Get users using search query & role
GET http://localhost:5501/users?q=runi